### ISSUE TITLE
There needs to be a localWorld variable for the part url

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#105]
The way to instantiate a part in lively.next is to use the following snippet:
resource('part://<worldName>/<partName>').read().then(morph => {
   // code to do whatever with the morph
});
Great!  This is much better than what we used to do.  But the problem is that the name of the world is hardcoded in the URL, and the name of the world can change -- when, for example, we save a variant.  So we'd really like something like:
resource(`part://${localWorld}/<partName>`).read().then(morph => {
   // code to do whatever with the morph
});
or
resource('localPart://<partName>').read().then(morph => {
   // code to do whatever with the morph
});

**Comment by merryman** [comment]
A local part identifier inevitably has the consequence that these parts can not be resolved any more from a different world. So importing components/parts into your world that use local parts then need to import these as well behind the scenes are else they will crash once imported. Furthermore I believe using localPart is harmful from a "policy" perspective, since it encourages people to define various duplicates of components within different worlds, which is exactly what we do not want to happen. Components should be defined in a single world, saving "variants" of a world is something we should avoid. Rather I would ask the question: What is the use case of different variants of a world, and from that we can derive a tool, that can help you achieve that without saving duplicates.

**Comment by rickmcgeer** [comment]
1.  When I'm collaborating with someone on an application, and I make a change, and I want to preserve the previous version easily, or when I'm not sure the change I'm making is a good idea (yes, I understand that Lively has a versioning system -- in my experience, it's awkward and cumbersome).  
2. When I want to do a new application that reuses a lot of a previous application, but the components aren't general enough for me to export them.
3. When I find a bug and want to leave the world with the bug in it undisturbed, but find a workaround and want to keep working.  For example, I'm now working on dashboardStudioTwo because of the bugs I hit in dashboardStudioOne (though in that case I copied components over)

**Comment by rickmcgeer** [comment]
And, actually, we can close this out!  We do have a localWorld variable I can use -- $world.name

**Comment by merryman** [comment]
Yes, that is quite true, but the problems I mentioned remain.
Regarding your use case:
1. Is due to a poor user interface and lack of a consistent way of versioning in lively in general, that we can fix. (move entirely to git, support meaningful diffing of worlds)
2. Exporting components != listed in the components browser. This is a thing we need to make really clear inside the documentation: Its fine to define as many components inside your world as you think is needed. Them being exported is also fine. What is not fine, is that the listing of the components gets cluddered, but each world can define by itself which components are supposed to get listed or not.
3. I am not sure I understand what the reason being leaving it undistrubed is. Do you find yourself ever going back to one of those worlds?

**Comment by rickmcgeer** [comment]
1. That would be very helpful on a number of fronts.
2. Robin, even if we did this (I'm not sure I understand it fully, but I'm sure you've thought this through carefully), re-using and modifying designs is a very common workflow in all sorts of areas.  For example, I have three different Galyleo Studio sales presentations, with a few slides that are different depending on the audience.  And this is also the way people learn to use tools and programming environments -- they start with something that is similar to the job they want to get done, and tweak it.  That's why Perl became so popular, even though it sucked -- no matter what job you had to do, there was likely a Perl script for it that was pretty close, and all you had to do was find and tweak it.  CPAN was a huge thing for Perl in the early days.  And if you've looked at Google Data Studio recently, you'll see there are a ton of templates -- these are designs people can tweak.  In practice, if we don't allow local references, people are going to over-publish components. 
3. No, I typically don't, but if I find a bug I want to leave the world with the bug in the state it's in so you can come back to it.

I hear your point about freezing.  But, believe me, tweaking worlds is something people will do, a lot.  They do it everywhere else.

**Comment by merryman** [comment]
Tweaking is not the issue I have. But dynamic resolved references to master components are not a good idea. I don't think that this is a necessity for tweaking.

**Comment by merryman** [comment]
I was thinking again how we can reconcile this in a meaningful way without messing up our build system or crowding the components browser:

1.) I propose fixing the build issue, by defining a declarative syntax for referencing components like you suggested. Instead of introducing a new resource identifier I would propose reserving the `$world` identifier within the url to always resolve to the local world, like so: `resource('part://$world/path/to/component').read()`. That makes the freezer resolve those references without a problem.

2.) The problem of saving variants of worlds: Right now if I save a world with a new name, all morphs within that world that are derived from local components will be referencing the master components in the "old world". We can fix that by either asking the user, or always default to readjusting the references to previously "local components" to now point to the components in the "new world".
We can also think about just by default always using the local identifier when working with tools or referencing components within a world in general. It would then be the job of the system to figure out that $world needs to be replaced by the world's name that defines those components when these get imported.
To illustrate via example: There is a **button/dark** defined within **System**. This component itself different local master components it references to define the look of the default/clicked/deactivated state of the button. Currently these are references by the absolute url, so something like `"styleguide://System/buttons/dark/clicked"` (you get the idea). Now if we were to replace these by `"styleguide://$world/buttons/dark/clicked"` which has all the benefits we talked about, we still need to make sure that when importing the component into a different world, the system adjusts these _dynamic_ paths to absolute ones automatically.

3.) It is not enough to just check references in our properties (that is basically refs via master), we also need to extract all dynamic refs inside the code of the components and replace these. Let me illustrate again on your concrete example:
What you are doing is defining a part that references components via this local syntax. This morph will inevitably break when it gets executed anywhere outside of that world, since if we ship the code without adjustments (as we do right now) it will encounter local refs to components that can only be resolved in the original world.
One nice thing about using absolute urls is that they work (naturally) in any context, and I would like to keep it that way.
I think we can solve this by scanning code that ships with morphs for local refs and auto replacing them on the fly before the modules and packages get imported in the new context. We will soon block editing foreign packages (make them read only) in outside worlds anyways, so that the only way of manipulating them is to explicitly fork. That way it also would not constitute a consistency error among worlds.

Let me know what you think. As of now, I do not see any more caveats. But that may change. This is huge change to the component system and we should be really careful in the steps we take.

**Comment by merryman** [comment]
Closing this since this has been implemented by now.
