### ISSUE TITLE
Copied parts lose properties

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#111]
I copied a part from dashboardStudoTwo to dashboardStudioThree, and the styling properties of some of the submorphs reset:
![image](https://user-images.githubusercontent.com/656259/100528427-ab5dc400-3191-11eb-9f56-578b3ab75748.png)

**Comment by merryman** [comment]
Hard to say what is going on here. Since you have been working a lot with variants of worlds and we have not yet implemented the dynamic local referencing of master components, that may have caused some odd behavior.
So first check that all the morphs that have master components reference the ones that you actually want them to reference.
Second, ensure that all morphs within the scope of a morph that is styled by a component have unique names. If for instance the labels that show "streaming" and "cached" have the exact same name and are also styled by a single master component, this will cause errors in the styling algorithm.

**Comment by merryman** [comment]
We now support warnings in case of name conflicts: ac54a11a9cf19b8f3b5e7926ca751d2b5ebcdc56
