### ISSUE TITLE
Revival fails when one has a lot of changed modules

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1303]
The sole number of files is probably not the reason, but we have no further idea what causes this.

![image](https://github.com/LivelyKernel/lively.next/assets/14252419/9012167d-3990-40c9-aa60-50a0b9cbedbc)

**Comment by merryman** [comment]
Leaving this here so I don't forget: from the investigation so far it appears to be caused by the improper handling of reexported modules via the `*` syntax. That is a `export * from "moduleA"` is not transformed correctly in the resurrection builds such that updates to `moduleA` are not propagated in the build.
