### ISSUE TITLE
Connection arguments

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#136]
I'm filing this ticket not because there's a bug but to get some clarification, which we can use in documentation.  I want to catch an event on a morph and use that to invoke a method on the morph's owner.  The signature on the owner method is:
foo(submorph) {...}
My question is, what should the arguments to connect look like, in particular the 5th argument.  My understanding is that the value passed in the argument is the value of the event, so, in:
connect(this, 'onBlur', this.owner, 'foo', v => ...);
What does the v refer to?  Does it refer to the event passed to onBlue?
My guess is the right invocation of connect is:
connect(this, 'onBlur', this.owner, 'foo', v => this);
in order to invoke
this.owner.foo(this);

**Comment by rickmcgeer** [comment]
So experimentation has suggested that best practice is simply to have a signal that something has changed, and then let the listener pull out any required information itself.  This is just accomplished with a property {derived: true, readOnly: true, isSignal: true}.  Adding to the pattern could be a listener structure, rather than connections....

**Comment by merryman** [comment]
Directly passing a function as the 5th argument is deprecated and should be avoided. What it does is define a _converter function_ which consumes the argument of the "onBlur" method call (in this case an event object) and passes its result to the "foo" method.

Regarding your invocation, yes it does what your were thinking. However, notice that this connection will crash once deserialized, since it does not know what to bind this against. This is the main reason this invocation is deprecated and you are encouraged to use the spec invocation instead:

```
connect(this, 'onBlur', this.owner, 'foo', { converter: v => u, varMapping: { u: this } );
```
