### ISSUE TITLE
Items don't move when I update position in Inspector

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#137]
I've been trying to set position manually in the inspector, by setting the x and y coordinates of widgets by hand.  However, as I do, the appearance doesn't change, as you can see here.  I've pulled the positions out so you can see they've been updated:
![image](https://user-images.githubusercontent.com/656259/103162302-ae090480-47a3-11eb-9631-4e1902ee89d6.png)

**Comment by merryman** [comment]
Manipulating the point objects themselves will not trigger a rerender. If you decide to do that, you need to manually call makeDirty() on the morphs that are supposed to be updated.
If we were to support what you want, we need to make objects like color, point or bounds be able to reference the morph they belong to directly or add connections between them and the morph they belong to.
This creates a couple of problems:
1.) If we go with the reference route, we need to add morphic specific code into the points, color or bounds class which is supposed to be separate from the morphic package. That means we need to create dedicated subclasses within the morphic package, like MorphicPoint, MorphicColor, or MorphicBounds that are able to do the auto update as you suggest. This however means we need to ensure and create new Morphic- specific geometry/style objects whenever the position, fill borderColor etc. setters are invoked, which is a performance overhead at a very delicate place in the system.
2.) If we go the connections route, we need to declare connections ephemeral, so they do not blow up the snapshots. That however means we need to create connections each time the setters are invoked, again creating even more performance problems.

Maybe these concerns are overly cautious, but if we are to introduce this update mechanism it needs to go through thorough testing so that memory and performance are not further compromised.
