### ISSUE TITLE
Scene graph pane confused on making connections

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#148]
I'm trying to make a connection from a list's selection to a method, which I've defined, but the method doesn't appear in the "Select Target Attribute" popup
![image](https://user-images.githubusercontent.com/656259/103448972-ef8f2900-4c55-11eb-9453-881dc33c5b72.png)

**Comment by merryman** [comment]
That's because underscore methods are considered private to the object and/or internal to the system. Connecting via a method equates with an outside function call. This is why we do not show methods that are named in this fasion.
Since you have considered __highlightChart__ a private method, why do you want to call it from another object? That is exactly what a connection does.

**Comment by rickmcgeer** [comment]
OK, got it, I will now make methods that connect to a UI element (even an internal one) visible.
