### ISSUE TITLE
Need line numbers in the Object Editor

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#152]
This is a fairly typical error trace: 
TypeError: Cannot read property 'filter' of undefined
    at NamedFilter.get (local://lively-object-modules/NamedFilter/index.js:74:39)
    at eval (local://lively-object-modules/Dashboard/index.js:252:60)
    at Array.map (<anonymous>)
    at Dashboard.__prepareFilters__ (local://lively-object-modules/Dashboard/index.js:252:33)
    at Dashboard.__prepareDataForChart__ (local://lively-object-modules/Dashboard/index.js:264:36)
...etc..
But the problem in tracing the error is that the line numbers are missing from the OE.  They are also not obvious in the browser, though they do show in the heading.  OTOH, when I look at the line numbers in the browser, they don't line up with the line numbers in the error message.  Line 252 in Dashboard/index.js is:
const table = this.tables[tableName];
which is not a map call and is in the __allColumns__ method.

**Comment by linusha** [comment]
This is something we also miss often. We talked to Robin briefly about this a few months back and he gave us some pointers on how to implement this, but we never had the time to really finish it, since lining the numbers and the lines up correctly in all cases (e.g., if a line breaks because it is too long and the window is too small) was quite complicated.

@merryman we will talk about this tomorrow I think, but we thought about having a "UX in lively Sprint" and this could be something we can discuss doing as a part of this maybe?

@rickmcgeer regarding the differences in the line numbers: The numbers in the error messages are from the "real JS" that actually gets executed by the browser. If you insert a `debugger` statement somewhere and look at the code in the developer tools after the breakpoint was hit you can see that some transformation occurs between that code and the one you wrote in `lively`. For technical details we would need Robins expertise.
**The takeaway is that if you need to look up a specific line number, hitting a breakpoint in the file and then looking at the code in the browser dev-tools should make it so that the numbers from the error message are correct.**

**Comment by rickmcgeer** [comment]
@linusha got it, this gets back to the issue of the lively debugger.  I personally find the Chrome debugger pretty unhelpful when I am debugging lively code, just because the correspondence between the code I wrote (ECMAScript, I know) and the code the debugger shows is not great.  Maybe this comes down to a feature request -- a tool that shows the OE/Browser Code and generated JavaScript side-by-side?

**Comment by merryman** [comment]
There is also an intermediate solution to this, which is to provide source maps together with the transpiled modules. However we have so far refrained from this, since that would balloon the memory and in particular indexDB footprint tremendously. Also generating source maps on the fly will at best not improve the speed that it takes to save a particular module.
If we were to introduce source maps, we need to do that with a "smart" heuristic which is not yet clear to me.

Regarding the lively debugger, we have a different tradeoff happening. In order to make it work, source code has to further be instrumented with try/catch clauses and other constructs that allow us to capture all of the scopes reliably if an error happens. After that the evaluation is dispatched to the debugger, which again is able to operate on the untranspiled code.
Again, we would need to devise a mechanism by which we can avoid to transpile all modules inside the system which balloons the transpiled source code size and also causes huge performance degregations. I was thinking about a toggle button that allows the developer to enable/disable debugger breakpoints for a particular module. However that could only be done after the fact.
Also remember that the lively debugger has limitations and that there is state in the system that is impossible to retrieve for us, i.e. variable bindings within closures.

**Comment by rickmcgeer** [comment]
I see.  It looks like this is not an easy-fix issue in the development environment, but it something that will take awhile.  So in the interim,  developers like me should use a best-practices method of defensive coding, and we should stick this into the bin of practices of how to write good code in Lively, along with how-to-use-connections and how-to-use-properties.

**Comment by linusha** [comment]
Closed, as the initial concern will be covered by #378.
