### ISSUE TITLE
Questions about component building and linking

### ISSUE THREAD

**Issue by DZL000** [LivelyKernel/lively.next#1539]
Dear devs of lively.next,

I am new to lively.next but have been playing with lively-kernel for the past few months. Along with few friends of mine, we have build a little project on lively kernel and are thinking about migrating the project to lively.next.

**What would you like to achieve?**
- I was curious about UI component building process within lively.next, so I set out to build some component from scratch with hope to establish better understanding on the anatomy of component and view model. 
- I attempt to build some simple component using both code and GUI.

**How are you trying to achieve that**
- I attempt to build a simple check box (similar to the one inside lively.components). 
- After some exploration, I am still pretty confused about the relationships between morphs, components as well as their view models.
- I figured out how to turn morphs into components using the button on halo, but how do you add view model to the component? 
  - Do I have to write code to achieve this? 
  - Can this be done through GUI?

**Alternative solutions**
_If applicable, what other solutions have you tried?_
- I have went through the code of checkbox component, and figure out how does the checkbox component works in code.
- However, in my observation I realise these code could be generated (I.e. when saving a component the specs would be saved as code). Is this correct?

**Additional Resources**
_Please provide links to any custom code that might be necessary to grasp your problem. Screenshots of custom component, etc. are also appreciated._ 
- I noticed the linking could only be done on morphs, when I try to link components together in the property panel, console outputs the following error. 
- Is this a bug or caused by my incorrect usage?
<img width="942" alt="Screenshot 2024-05-24 at 10 53 45" src="https://github.com/LivelyKernel/lively.next/assets/58769867/2708aef6-9834-4611-967e-d94ecb510502">
<img width="594" alt="Screenshot 2024-05-24 at 10 54 02" src="https://github.com/LivelyKernel/lively.next/assets/58769867/5862b88e-5e25-4720-a7ac-99b2e4f6d9ca">

**Version**: _Please paste the lively.next commit on which the problem occurred here (use the copy button of the VersionChecker in the bottom left corner)._
- fbfad04c7a23793879b9c14bd366188eeea48055

Thanks for your attention, I'm looking forward to your reply!
DZL000

**Comment by DZL000** [comment]
Hello @linusha and @merryman,

I wanted to provide an update on the questions I raised last week.

After going through the project wiki, I now have a better understanding of the relationships between morphs, parts, components, and view models. As a result, some of my previous questions can be disregarded.

However, I still have a few remaining queries:

1. **Adding View Models to Components**:
    - Do you need to write code to integrate a view model into a component?
    - Is there a GUI available for this process, such as tools for component linking and a component status property panel?
Best Practices for Building Custom Components:

2. **What are the recommended procedures for building custom components?:**
    - Would it be possible to provide a short video or tutorial demonstrating the component building process in Lively.next? 
    - For example, a tutorial on creating components like a thermometer, temperature converter, magic wand, checkbox, etc., would be extremely helpful.

Thank you in advance for your assistance!

**Comment by merryman** [comment]
@DZL000 Thank you for your patience and also the effort you went through figuring this out on your own ;-). As you can probably tell a lot of your questions could have been addressed by a better documentation and instruction material. The good news is that this is precisely what we are working on right now. The bad news is that's it's still a couple months of work until it's done. So let me try to address the questions you mentioned:

1. regarding the view models, yes there is a little bit of code that is needed to attach them to instances of a component. This is done inside the component's definition itself, like so:

`const ComponentA = component({ defaultViewModel: ModelA, ... })`

Then any morph onstantiated from this component will have a `ModelA` instance  attached. 

Now we are also planning for a visual way of doing this in the future that will be similar to the object editor workflow, but that's not yet ready for prime time.

2. we are working on addressing this exactly this very moment. For the time being, the best practice would be to look for existing components that may already suffice your needs. And if not, figure out if it's just visual or behavioral. Depending on that, purely visual concerns can be easily addressed by deriving a custom component from the existing one. Behavioral is more tricky, and I would suggest 80% of the time to build your own view model from scratch rather than deriving an existing one. I would also advise you to be careful relying too much on the declaration of components via the halo interface since that is still buggy and we are continuously fixing pressing issues as of now. If your are welcome contributing to alpha testing go ahead, but if I was working on a project I would first declare an empty component via code and then use the halo interface from there.

**Comment by DZL000** [comment]
Thank you so much for your thorough explanation and recommendation! 
It clears thing up a lot 😄
