### ISSUE TITLE
Very weird behavior (possibly component-linked?)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#154]
The world is Dashboard Studio Four, and it started when I componentized everything.  Charts initially draw as they are supposed to, but then reverts  back to the rendering of the original component.
Here is what the chart should be:
![image](https://user-images.githubusercontent.com/656259/103977706-a98f0500-512e-11eb-8af8-269dd9d0a1b7.png)
And after I edit it, that's what I see.  But after I move the mouse on the screen, it reverts to this:
![image](https://user-images.githubusercontent.com/656259/103977787-d511ef80-512e-11eb-9c85-43925e4907d9.png)
Which is the image of the master component, here:
![image](https://user-images.githubusercontent.com/656259/103977844-f541ae80-512e-11eb-9501-0abc35ec210f.png)
Any thoughts on what is causing this would be appreciated.  I've looked for stray connections, etc., without success.

**Comment by rickmcgeer** [comment]
One note is it didn't happen on the non-componentized version.  As far as I can tell, the code is nearly identical.  The non-componentized version is in https://matt.engagelively.com/worlds/load?name=Dashboard%20Studio%20Four-Old

**Comment by rickmcgeer** [comment]
Componentized version is in https://matt.engagelively.com/worlds/load?name=Dashboard%20Studio%20Four

**Comment by merryman** [comment]
The answer is quite simple, but we should discuss how to avoid this situation: 
The `html` property of the HTMLMorph is considered a style property and can therefore be controlled by the master component.
We usually avoid this problem you are encountering by overriding local properties of an instance of a component that we do not to be styled as such.
Notice however that when you open the styling palette, it does not list html as one of the overridden properties, so eventually the derived chart morph will revert to the html of its master component.
The reason why html is not considered overridden is because nowhere in your code to you explicitly set html after the chart has been initialized. Rather you just pass the responsibility of patching the html node behind the scenes off to google charts.
That however circumvents our tracking mechanism that detects overridden properties.
So the fix here would be to at one point during chart initialization, to set html to some value (maybe `defaultHTML`) that tells the system to consider html not part of the styled properties any more.

I am open for other suggestions. We can think about removing `html` from the set of style properties, but I can think of a lot of scenarios, where it is in fact quite convenient to have the html be synchronized across all instances.

**Comment by rickmcgeer** [comment]
As far as I can tell, there are two fixes, both of them at the level of the application developer:

1. As you say, put in a `defaultHTML` setting for a library instantiator like google charts, maps, etc.
2. Don't use the component system for libraries.  This actually won't work very well, since components replace the PartsBin and we want to reuse the code

The other fix is to explicitly override the style property -- this would need a decorator of some sort..

**Comment by rickmcgeer** [comment]
Actually, this leaves me with a couple of questions:

- `defaultHTML` is set in a property; should I set `this.html = this.defaultHTML` in `onLoad()`?
```
      defaultHTML: {
        derived: true,
        get () {
          return `<div id="chart-container-${this.id}"></div>`;
        }
      }
```
- googleChartMorph is a component in https://matt.engagelively.com/worlds/load?name=Dashboard%20Studio%20Four-Old but I am not seeing this behavior there.

**Comment by merryman** [comment]
1.) Yes that could be an option.
2.) Yes it is indeed a component but what you are doing is not creating a derived morph of that component but you just duplicate the component itself, which is the same as just working with a part.

**Comment by rickmcgeer** [comment]
That fixed it!
```
init(chartName) {
   this.chartName = chartName;
}
```
became:
```
init (chartName) {
    this.name = chartName;
    this.html = this.defaultHTML;
}
```
As I say, this is only an issue when incorporating a library which writes HTML, and I think we solve this by documenting the right pattern for programmers who do this (a small number).

**Comment by merryman** [comment]
All right, I am closing this then.
