### ISSUE TITLE
Wrong CDN URL

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#1653]
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/47e23744-0aa8-490c-9e8f-378e3e1bee1e">

elkjs url:  https://cdn.jsdelivr.net/npm/elkjs@0.9.3/+esm

ref: https://www.jsdelivr.com/package/npm/elkjs

**Comment by merryman** [comment]
Yes, this is an issue with jsdelivr. They have a wrong url in one of their generated dynamic imports. You can fix this by adding `mermaid-it-markdown` to the `excludedModules:` list in the buildscript at `./tools/build.mjs`.
@linusha I will look into if there is easy way out here, this particular package seems to cause quite a bit of a headache.

**Comment by linusha** [comment]
Isn't the solution quite straight forward? In any case it is of course unfortunate that the code we retrieve from the CDN is erroneous, but since one does not want to bundle `mermaid` in any case, isn't the problem here mainly that we have not yet put the updated build script on `main` but only on our dev branch? Once we "officially release", i.e., merge back into main, this should be gone for everybody, no?
