### ISSUE TITLE
Unable to render markdown

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#1654]
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/f5cfe502-4607-4df8-aee7-de21b7ad17e0">

hi , I am a Smalltalk user and I like the liveness of Lively.

When I encounter errors while working in lively, how do I fix them within lively?

**Comment by merryman** [comment]
Hey @wwj718. As a general rule of thumb if you encounter an issue its worthwhile trying to load lively again with the fast load disabled. You do that by adjusting the fastLoad parameter in the URL to `false` and reloading via the browser. This should fix the issue you are reporting above. Also you will be able to debug more easily since each module is its own file.
I will be starting to work a bit on supporting source mapping in August, so maybe we will have proper source maps support by September or so.

**Comment by linusha** [comment]
Regarding `fastLoad` and "slow load", you can also change the default that `lively.next` uses when you are opening projects via the dashboard, @wwj718. We refer to what you see when loading localhost:9011 as the dashboard. In the bottom right corner there is a button showing either a hare or a turtle. It might be hard to see at the moment, due to #1655. If the hare is visible, opening a project will fastLoad it, while the turtle will slowload. For developing the core, slowload is recommended. This setting should get preserved inside of your browser. Setting the URL parameter explicitly will overwrite this setting.

**Comment by linusha** [comment]
@wwj718 what I wrote above is still true, sorry, I wrote in the wrong tab without thinking...

We will fix the underlying problem of both this and #1653, but the problem is a bit harder than we initially thought and we need to prioritize the finalization of the website, which we are currently working on. Dev capacity will go drastically down over the next few weeks, but after tomorrow, this has upmost prio!
