### ISSUE TITLE
Selection of multiple code lines with mouse

### ISSUE THREAD

**Issue by T4rikA** [LivelyKernel/lively.next#200]
The selection of multiple code lines in the browser is no longer possible. The problem may have come through #193

**Comment by merryman** [comment]
Yep, I managed to fix this on my machine by using buttons instead of button inside the event/Event.js: 
I still dont fully understand whats going on. Maybe plattform specific? @linusha 
```
 // mouse buttons, see
  // https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
  leftMouseButtonPressed () {
    return this.domEvt ? this.domEvt.buttons === 1 : false;
  }

  rightMouseButtonPressed () {
    return this.domEvt ? this.domEvt.buttons === 2 : false;
  }

  middleMouseButtonPressed () {
    return this.domEvt ? this.domEvt.buttons === 4 : false;
  }
```

**Comment by T4rikA** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button says, that `buttons` return which buttons are pressed for all mouse events types, in comparison to `button`, which is the button that triggered the event.

**Comment by linusha** [comment]
I think the key-point is this one:

> The MouseEvent.buttons property indicates the state of buttons pressed during any kind of mouse event, while the MouseEvent.button property only guarantees the correct value for mouse events caused by pressing or releasing one or multiple buttons. 

From my understanding this leads to hickups with the selection since that is not triggered by a simple press/release, but is a dragging motion. Since the docs also state that `buttons` guarantees the correct value for all kinds of mouse events, the solution posted above by @merryman seems good to me. 

`buttons` would also allow for more complicated scenarios, e.g. we could also find 3 as the value in the case that both the left and the right mouse-button are pressed (all values less than 32 are possible, with 31 being all buttons pressed on a mouse that has two additional buttons at the side). However, the solution from above should fix the current problem, the other possibilities we can just keep in mind :slightly_smiling_face: 

Can you just push this, if you have done the changes already, @merryman? Otherwise I'll prepare a PR!
