### ISSUE TITLE
Directory in module list

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#211]
The browser module list should support a file browser like experience with folders and subfolders that may be expanded or not.

**Comment by merryman** [comment]
This can be easily achieved by replacing the list with a tree instead. For inspiration, take a look at how the file browser is implemented. I think the file view can actually be directly used inside the browser with little modification.

**Comment by mayureshkathe** [comment]
I'm new here, but I do have 30 years of industry experience to back-up my suggestion below.
Please stick with list view instead of a tree view because while tree view might seem appropriate for a graph structure they tend to breakdown for structures with high degree. Do consider implementing "Miller columns" along with a "shelf" (as was used in NeXTSTEP). Please take a look at the Wikipedia entry; https://en.wikipedia.org/wiki/Miller_columns

**Comment by merryman** [comment]
Next on my todo list is an update to the system browser. Honoring @mayureshkathe suggestion it will basically add a miller column interface that includes packages and folders in addition to modules and module namespaces. Also It will revamp the rather confusing interface of the system browser, removing useless button, clarifying what adds packages, folders or modules and provide a general facelift to the UI.

**Comment by mayureshkathe** [comment]
@merryman I'm glad I could be of some use at the moment. Please remember to develop a shelf-like space attached to the Miller-column mechanism. Only then would that system be complete and hence vastly more usable than tree-view or Miller-columns alone.

**Comment by frcroth** [comment]
Now implemented with miller columns
