### ISSUE TITLE
Halo overlays context menu

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#22]
The active halo of a Morph overlays the context menu of same Morph which appears after right click. I expected the context menu to overlay the halo, since I opened the context menu after activating the halo.
![grafik](https://user-images.githubusercontent.com/44174681/96720795-82d0f600-13ab-11eb-8513-ca3790a70d51.png)

**Comment by merryman** [comment]
Halos currently carry a specific css class ("halo") that makes them always appear on top of everything.
I am open with experimenting assigning menus to that same category of elements since they play a similar role.
However we have found overlapped halos to be quite annoying when working with parts, which is why this measure was taken.

**Comment by linusha** [comment]
This is not the current behavior anymore.

![image](https://user-images.githubusercontent.com/14252419/196717278-93a7fdfa-d969-44ef-b9c2-8a8f239f7883.png)
