### ISSUE TITLE
Morph currently edited by the Styling Palette is not entirely obvious

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#312]
This is an issue that we opened some time ago in a project-internal repository, when working on the comment browser. It makes more sense to move it here. Unfortunately, we have not had a solution in mind already.

**Comment by merryman** [comment]
Looking at how other editors solve this I think the key is to couple tools like the styling palette more strongly to the active halos. That means, in cases where no halos are present, the styling palette wont be able to change things. If a halo is present, the selected morph is the one who is getting changed.

Now the reason why this has not been done properly yet, is because we have to think through some special cases:
1. When we start editing a text morph, we usually loose the halo as a result. This however means that we cant really change text attributes via selection/editing the text. My current solution is that halos can transiently enter a "edit text" mode where they open up the rich text editing capabilities of a text morph temporarily. This mode can be entered by double clicking a text morph.
2. You don't want to lock halos. When the user clicks somewhere empty on the world *or something that does not yield a halo at all*, the expectation is that the halo is removed. However, when interacting with tools like the styling palette or the color picker, we do not want halos to disappear despite these tools to not default to a halo, because that would mean we loose focus as soon as we start interacting with the tool. However we still want to be able to conveniently inspect such tools with halos as well (when we find bugs or are just curious to learn about the system, hence `halosEnabled = false` is a very bad idea in general). Right now there is no "clean" abstraction in the system that handles this differentiation. There is a flag implemented in morphs called `isHaloItem` which was initially intended for preventing the halo from killing itself, but the naming is **A.** Quite unfortunate since a color picker is not really a halo and **B.** Right now it only applies to a morph in isolation. All siblings and parents may still yield halos if clicked on if not also setting `isHaloItem = true`. `withSumorphsDo()` is the immediate answer but still. It seems a little quirky to me. Maybe `isHaloItem` should recursively apply to all its siblings.

**Comment by merryman** [comment]
Given the updated style side bar I think this is no longer an issue.
