### ISSUE TITLE
Part opacity getting reset to 0 on load

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#331]
The world is https://matt.engagelively.com/worlds/load?name=DAN3.  I added a new public component  to https://matt.engagelively.com/worlds/load?name=Sliders, which I then used in four components in DAN3, namely:
bmiCard, healthCard, experienceCard, equipmentCard.  In three of those four components (all except equipmentCard), when I reload the world the sliders have opacity 0.  When I browse the components they all have the sliders appearing as they should.   When I manually reset the opacity to 1, it's fine, but when I reload it goes back to 0.
Suspecting a bad component, I renewed it, and then saved the world as DAN4.  Same problem.  Eventually I reinstantiated the screen component, but then the text problem I had earlier re-appeared.

The component architecture has issues.

**Comment by merryman** [comment]
When I load that world all slider appear without a problem. The components are very prone to flaky internet connections. If a component fails to load for whatever reason it may cause the derived morphs to be transparent. This will be greatly improved when we transition to source code based master components since those are loaded via the module system which has a more  error proof fetching mechanism.

**Comment by merryman** [comment]
I am closing this one since the preliminary transition to file based master component definition is nearing completion.
