### ISSUE TITLE
Sidebars should have a click to collapse or expand

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#51]
Using the top menu is somewhat nonstandard and unintuitive

**Comment by merryman** [comment]
Would you suggest flaps? Open for suggestions.

**Comment by linusha** [comment]
I began working on this quite a while ago and kind of forgot about it.
What I have looks like this, here as an example for the styling palette:
![right_flap](https://user-images.githubusercontent.com/14252419/103463498-1a987c00-4d2d-11eb-83a6-f9557ee38588.png)

Please ignore for the moment, that the caption is not centered, etc. I will take care of this when we agreed that this is a viable solution.

If you guys @rickmcgeer and @merryman think this would be nice, I have some questions regarding the implementation that I would like to discuss:
- As of now the sidebars are only really usable while the topbar is loaded. Is it intended to be kept this way? (Personally I think that this makes sense, but I have no hard feelings either way^^) I just ask because then I would just use the same method for opening/closing the sidebars as the topbar.
- When the sidebar is closed I currently keep the flap at the same height (fixed, so it stays there when scrolling in a high world) to open it. This is the essence of this ticket, but somehow this feels quite intrusive to put a button right there in the world all the time. I would suggest to have a setting in the config where these buttons can be toggled?
- Robin, would you like to have these kind of flaps as "clean" UI Elements? Or can they be very sidebar specific right now i.e., the labels, icons, methods,... are not set via code but part of the flap-components.

Just let me know what you guys think of it and I should be able to finish this relatively soon :)

**Comment by merryman** [comment]
Overall I am open to experiment with this. I especially like that we can get rid of another button from the menu bar. However I am not sure if the white works with the side bar. Maybe change the flap to a similar black/transparent background with white font instead?
