### ISSUE TITLE
Component Declaration and Internal Management

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#534]
- Components are declared via Halo interface.
  - [x] At first the component name declared the file name that is created and the component is defined in.
  - [x] The halo interface ensures that there are not name conflicts within the project.
  - [x] Components without parent components reside in their own file
- All derived components are defined via copy halo interface.
  - [x] Once they are declared to be components, they are placed in the same file as their parent.

**Comment by merryman** [comment]
How are we going to organize the defined components for a project? I feel like neither the components browser nor the System browser provide a really convenient way for a designer to craft components.
It feels more like:
1. System Browser for last minute or very minor corrections that are done in case issues are detected just before the thing goes live.
2. Component Browser: for "browsing" and exploring "whats there" (candy box) but also for quickly getting a hold on elements that can be reused to define new components. Not a super cool way to get a hold of the projects local components. Especially, since the component browser will always yield parts and never the components themselves when dragging or importing them into the current project.
3. So there needs to be a third view, which lays our the projects component morphs visually in way that resembles figma? Maybe each file gets a tile in the world and then automatically lays out all of the components it comprises? Maybe there is a interactive way to toggle these so that the user is not always forced into having huge swaths of components open at the same time?
