### ISSUE TITLE
Weird behavior from ECMAScript (not a lively issue, but this is something to watch for...)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#580]
In module `galyleo-data.js`,  I defined:
`export async function constructRemoteGalyleoTableFromConnector(tableName, connector) {...}`
Then
`import { constructRemoteGalyleoTableFromConnector } from "galyleo-data.js"`
returned `undefined`

OK, that's weird.  So try:
```
async function constructRemoteGalyleoTableFromConnector(tableName, connector) {...}
export { constructRemoteGalyleoTableFromConnector }
 ```
import is still undefined.  OK...
```
const constructRemoteGalyleoTableFromConnector = async (tableName, connector) => {...}
export { constructRemoteGalyleoTableFromConnector }
 ```

works fine.  Honestly, this is weird.

Look, this isn't Lively, this is ECMAScript, and I just needed someone to complain to.  Go ahead and close this out...

The only action is _best practice with ECMAScript is not to use the function keyword!_

**Comment by merryman** [comment]
This is not an EXMAScript problem. If anything this is an issue with `lively.modules` and our implementation of the module system. But anyways, what I do not understand is how you could have ended up with a successful import via `from "galyleo-data.js"` since that is requesting a module that is directly located at the root directory of lively.next.
I assume that what you would have wanted instead was a `import { constructRemoteGalyleoTableFromConnector } from "./galyleo-data.js"` and use a relative import `'./'` since this module is part of the `galyleo-dashboard`.
If A. `lively.next` did not throw an error when you tried to save `import { constructRemoteGalyleoTableFromConnector } from "galyleo-data.js"` or suddenly allowed you to import it successfully after any of the changes you mentioned above, this is extremely problematic. Can you try to reproduce these steps? I believe when you try this again, you should not even be able to successfully save the import.
