### ISSUE TITLE
Tracing connections...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#585]
This is derived from a GalyleoDashboard issue.  Briefly, it would be  convenient for a user to know what signals a morph/object supports and what the current connections are.  Perhaps this is done today (I certainly hope so!) but I'd like some guidance on how to discover an object's signals and current connections.

**Comment by merryman** [comment]
You have already reported this issues (rightfully) before: #163.

The short answer is that we currently do not have a definitive answer to this problem since it is deeply connected to the problem of supporting tinkering and engineering workflows. I outlined that a little in this discussion: https://github.com/LivelyKernel/lively.next/discussions/338.

The inspection of *instantiated* connections at runtime and the dynamic initialization of connections to live objects relies heavily on being able to productively work with snapshots, which currently does not scale beyond a single individual working on their own. This is what I sometimes like to refer to as *tinkering*.
So we could invest time into this workflow and throw more tooling on it, but it is a little futile since we are hamstrung by the fact that eventually all things fall apart when we want to work in teams.

So we are currently pondering a new way to work with connections wich either (1) only allows to define connections via the new `bindings` mechanism in the view model architecture (keeping connections locked away in source code) or (2) works through some kind of reconciliation mechanism similar to component definition, where either bindings or some other canonical piece of code is rewritten in response to drawing a visual connection between elements through a halo interface.
