### ISSUE TITLE
`without` isn't working in components

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#586]
For GalyleoDashboard, we want an abbreviated form of the Top Bar, and @merryman designed it that way.  The code is:
```
const GalyleoTopBar = component(TopBar, {
  name: 'galyleo/top bar',
  fill: Color.rgb(208, 211, 212),
  defaultViewModel: GalyleoTopBarModel,
  submorphs: [
    {
      name: 'horizontal layout',
      submorphs: [
        add({
          type: Image,
          name: 'galyleo logo',
          borderColor: Color.rgb(23, 160, 251),
          extent: pt(245.4, 116.6),
          imageUrl: 'https://i0.wp.com/engagelively.com/wp-content/uploads/2019/12/galyleo-logo.png?fit=700%2C320&ssl=1',
          naturalExtent: pt(700, 320),
          reactsToPointer: false,
          scale: 0.2505891168205277
        }, 'halo mode button'),
        without('open component browser'),
        without('comment browser button'),
        without('load world button'),
        without('load world button'),
        without('undo button'),
        without('redo button'),
        without('save button'),
        {
          name: 'text mode button',
          visible: false
        },
```
See:
```
$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "galyleo-dashboard", });
```
However, the screenshot of a Galyleo Dashboard looks like this:

![without-bug](https://user-images.githubusercontent.com/656259/207889151-5fa44a97-1b42-40c9-b85d-2d958f52289d.png)

As you can see, the undo, redo, component browser, comment browser, load world and and save world buttons are still there.

**Comment by merryman** [comment]
The problem is that the top bar does not have a submorph called `'horizontal layout'` anymore.
There was a recent change that renamed that morph to `'tiling layout'`. So you need to reference that name instead.
This is one of the problems with the component architecture to which I have not yet found a good solution.
I guess the first step would be to make the user more aware that a referenced submorph is no longer present for changes to the master component definition. That should happen at component definition time, so that a user would be made aware if incorrect changes are entered or a once fine module can no longer load properly.

**Comment by rickmcgeer** [comment]
I tried this, no luck.  'tiling layout' fails as well
The simple workaround for a user is to just open up the original component definition in a new browser pane.  This is the principal use case for multiple panes in (for example) VSCode.

**Comment by rickmcgeer** [comment]
It did work!  It must have been a cache issue (once I reloaded the project the top bar worked as @merryman said it should
