### ISSUE TITLE
Timing issues in Number Widgets

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#587]
The specific case where this happens is written up in https://github.com/engageLively/galyleo-dashboard/issues/134.  The RangeFilter in GalyleoDashboard has two number widgets `minInput` and `maxInput`, and the constraints are that both should be within the maximum/minimum bounds for the filter and that `maxInput.number >= minInput.number`.  Ensuring within the bounds is working fine; however, the code
```
if (minInput.number >= maxInput.number) {
    minInput.number = maxInput.number;
}
```
Is being executed, but this is not reflected in the values shown in the widgets
I suspect a timing issue.

**Comment by rickmcgeer** [comment]
It may be that there is a better way to accomplish what I am trying to do, e.g., resetting the bounds on the other input...

**Comment by linusha** [comment]
As far as I can see, this has nothing to do with the Number Widgets.

First off all, although that should not influence functionality - on which commit of lively are you working? We recently changed the name of `NumberInputDark` to `DarkNumberIconWidget`. This influences your `GalyleoNumberInput`, in case you have that change incorporated in your fork/branch. So this is just something to watch out for.

Now, I do not know how to instantiate the whole dashboard project correctly, thus I just pulled the most recent main branch and did `part(RangeFilter).openInWorld()`. Afterwards, I called `init()` on the resulting _range filter_ with appropriate values for `min` and `max`.

In my opinion, the problem is that you use the `bindings` property here, although `RangeFilterMorph` is a subclass of `Morph`. As far as I see, this property only works with subclasses of `ViewModel`. So you can either rewrite the `RangeFilterMorph` class to be more like a proper ViewModel, or instantiate the connections via `connect` in `init` again.

**Comment by rickmcgeer** [comment]
@linusha, thanks!  This wasn't working at all before I added `bindings`.  However, further investigation revealed that we still have the issue, which I traced to a failure to update in the `NumberWidget` -- which I confirmed by instantiating `DefaultNumberWidget` standalone. I reported this in #588.

I'm on commit  d1516ca20279481bba8529d038e7ba80e266ca83, November 10.
