### ISSUE TITLE
The shortcut menu items are not really decipherable to me

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#59]
![image](https://user-images.githubusercontent.com/656259/98048875-6d17f380-1de3-11eb-8a52-5e0c15caa972.png)

**Comment by linusha** [comment]
This seems to me like another step in the larger overhaul of the menu.

I somehow agree with the assessment of @rickmcgeer, but I think the optimal solution would be to make this platform dependent. E.g. on a mac I think the existing labels are fine, since the symbols directly map to existing keys. For non-mac users these symbols are not easy to read and also (mental) remapping is required, since these keys do not exist 1:1 on non-mac keyboards.
(_Disclaimer_: I do not own a mac, so please correct me if I this is incorrect).

I stumbled upon the code that creates these shortcut descriptions a while ago IIRC and would like to dive into that, so I will try to look into this.

@merryman do you think checking `window.navigator.platform` would be an appropriate way to figure out the current platform? (I am not able to look into the code right know, apologies if there is something internal already!).

**Comment by merryman** [comment]
@linusha Yes I agree with most of what you pointed out. For checking the platform we usually use the bowser module (you can check that by code searching for bowser), so I would prefer that. Regarding the best entry point, check this out: `$world.execCommand("open browser", {moduleName: "lively.morphic/morph.js", codeEntity: "keyCommandMap"});`
