### ISSUE TITLE
Need guide for imports and getting them into Lively

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#592]
Typical tutorial examples for importing libraries use the HTML5 script tag, e.g.:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
```
We instead use jspm, which unfortunately doesn't give a lot of insight into the API.  So then the question is, how do we resolve namespaces?  The obvious thing to do is use a line like:
```
import * as chartjs from 'https://jspm.dev/chartjs@0.3.24';
```
but that fails, as does the other reasonable assumption
```
import { Chart } from 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.1/chart.js';
```
which gives this:
```
Error: (SystemJS) Cannot read http://127.0.0.1:9011/@kurkle/color: Not Found 404
	Error: Cannot read http://127.0.0.1:9011/@kurkle/color: Not Found 404
	    at WebDAVResource.WebDAVResource_read_ (http://127.0.0.1:9011/lively.resources/src/http-resource.js:591:23)
	    at async SystemJSLoader.fetchResource (http://127.0.0.1:9011/lively.modules/src/resource.js:35:33)
	Error loading http://127.0.0.1:9011/@kurkle/color as "@kurkle/color" from https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.1/chart.js
```
Also fails.
In every version of Lively, this has been murky and undocumented.  We need to fix this this time.

**Comment by rickmcgeer** [comment]
I also tried simply downloading the thing, but the dangling reference to color got me

**Comment by rickmcgeer** [comment]
What I have done in the past is to use an HTML Morph so I could put a `<script>` tag in, but I'm sure this is not optimal.

**Comment by merryman** [comment]
JSPM attempts to expose the exact same import behavior as if you were to install the respective package locally and resolve it via npm. So let us clarify some things here.

Scripts such as `'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js'` are not meant to be imported in another module. There are multiple reasons for this. For one these modules are bundled in a format that allows them to be run in the browser and populate the global namespace so that their functionally can be accessed from anywhere in the client runtime.
That also means they do not provide a straight forward syntax that allows us to discover exports easily. SystemJS (which our `lively.modules` is build upon) comes with a mechanism which at runtime detects the exported entities of a global module and therefore expose them via the module interface. So we can technically import these modules in lively if we want to. However since these modules bundle all of their dependencies, it is generally a bad idea to import them into your project since you likely pull in large amounts of duplicate code. So it is always more preferable to import the ESM modules from jspm if possible.
The reason the global import `import { Chart } from 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.1/chart.js';` failed is because this module appears to be broken. It still contains imports that can neither be resolved nowhere on the cloudflare server. Maybe that module is not supposed to be imported at all.

On another note importing `import * as chartjs from 'https://jspm.dev/chartjs@0.3.24';` does in fact work very well. It is just a different package than the `chart.js` you were referencing in the other two examples. I believe you were mixing up packages here.

**Comment by merryman** [comment]
On a more general note, the `lively.modules` right now fails silently when certain exports of a module do not exist. I think we can do better than that, by:
1. Do log a warning if there are imports that could not be satisfied.
2. Give some hints about wether or not the import approach is doomed to begin with, i.e. some packages simply expose all of their entities via a default export.
