### ISSUE TITLE
We need a Dock for iconified windows...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#609]
In every Lively session I've ever had (for 10 years!), I wind up with iconified windows that are scattered all over the studio, and (further) it's hard to tell which iconified window is for what -- if I have three inspectors open, which is for what object?
I suggest that iconified windows be stored in rows at the bottom of the screen, similar to the taskbar in windows and the dock in MacOS, and, moreover, that the icon title either contain the name of the object or the object appears in a hover

**Comment by merryman** [comment]
I am not entirely sure how the dock fixes that. How for instance does the dock fix the problem of what inspector is linked to which object in the scene? Is this not more deeply related to the way the inspector is implemented right now?

**Comment by linusha** [comment]
@merryman I think @rickmcgeer might clarify this for us, but I am pretty sure that those are different feature ideas.

1. A dock at the bottom of the screen holding all iconified windows.
2. The titles of windows and thus of the iconified windows need to contain better information, i.e., the name of the inspected object for inspectors. This is definitely an issue and I noted that down with an emphasis on browser in the past (#378).

I am fully on board with 2. I would also propose that we maybe add an additional button to the inspector which `shows` the current target object? De facto the reverse of the "bind to new target button" we currently have?

---

As for the dock, I will think about this some more, but I think it is important that this does not take up screen estate when it is not currently used. Otherwise, I fear we are running in a situation where we take up too much screen space with all our tooling (topbar, sidebars, minimap,...)

**Comment by linusha** [comment]
Until further notice, #670 solved this.
