### ISSUE TITLE
Browser renders text longer than 65552 characters wrongly

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#654]
When inserting very long text into a text morph, "ghost characters" (i.e., whitespace) will be inserted around the above mentioned character count. This also happens with native span elements on a blank HTML site. I.e., it is a browser problem, not a lively problem in the first place.
What exactly happens is dependent on platform/fontsize/maybe lineheight.

![ghost-paragraph](https://user-images.githubusercontent.com/14252419/214339135-572b6ff4-c686-414b-99fc-704b8b34cd1b.gif)

VS Code does not have this problem, since they implement their own line wrapping and thus have less characters inside of their span elements per line.

We can either do that too, or just disallow having text with that many characters in a single line.

This problem make it seem, as if the character measuring is off, but this is only due to the ghost character that we cannot anticipate.

:dog2:

**Comment by merryman** [comment]
It appears this could be alleviated by splitting up chunks that are longer than a reasonable threshold into smaller pieces (10k characters maximum each). When we render each of the sub-chunks inside a separate span, then this artifact by the browser should not occur any more. Lines are still properly laid out, since we implement them by a custom div tag that contains said spans.
