### ISSUE TITLE
Morphic properties menu

### ISSUE THREAD

**Issue by Paula-Kli** [LivelyKernel/lively.next#74]
Since fixing #72 draggable is not checked anymore and the property draggable is set to `false`.
![screenshot1](https://user-images.githubusercontent.com/49535291/98812741-4bda8700-2423-11eb-855b-f553c3f8b489.png)

Is there a reason for that? Also why is grabbable always set to `false` and nevertheless morphs are grabbable?

**Comment by merryman** [comment]
The properties `grabbable` and `draggable` allow morphs to be grabbed (pulled out of their current parent child relationship) and dragged (moved via mouse/touch down and drag) out of the box. You can confirm that by selecting the Hand (Mouse Interaction Mode) in the top bar and trying to grab or drag the morph. You should not be able to do that. What you were probably referring to however is the fact that you were still able to move and place the morph with the *halo* selected. This is because halos override the grabbable and draggable property in order to still allow the user to manipulate all elements when needed. I hope that clears up things!
