### ISSUE TITLE
`$world.inform` clips wrapped lines since it wraps by words. Should wrap by-chars instead.

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#758]
**Describe the bug**
The accompanying screenshot makes it clear.  The text to show was `The URL is https://galyleo.app/dashboards/0/drilldown-test.gd.json` and everything between the "0/" and "test" was cut off.

This isn't a major issue.  It's easy to create a component that will popup and adjust to accommodate a string, which is what I'll do.    But I thought you'd want to know.

**To Reproduce**
Just create a `$world.inform()` with a sufficiently long string.

**Screenshots**
![Screenshot 2023-03-09 141935](https://user-images.githubusercontent.com/656259/224175244-e9cad300-4ae0-4f58-9305-31d99470e47d.png)

**Setup**
Please check the applicable boxes:
- [ ] macOS 
- [ ] Linux
- [x ] Docker
- -[x] Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (short version from the Version Checker in the bottom left corner is sufficient).
0e22dbdb9416630eaf14c02b4da607af029b508d

**Comment by linusha** [comment]
> This is because you did not pass a proper `lineWrapping` argument. I guess the default should not be `true` (as it is now) but something like `by-chars`. At any rate, if you do a `$world.inform(message, { lineWrapping: false });` it should display the message properly.

@merryman so we change the `defaultValue` in `Text` to be `by-chars`, yes?

**Comment by merryman** [comment]
In the InformPrompt that is.

> > This is because you did not pass a proper `lineWrapping` argument. I guess the default should not be `true` (as it is now) but something like `by-chars`. At any rate, if you do a `$world.inform(message, { lineWrapping: false });` it should display the message properly.
> 
> @merryman so we change the `defaultValue` in `Text` to be `by-chars`, yes?

In the `InformPrompt` that is.

**Comment by linusha** [comment]
@rickmcgeer We tested changing the default value in all prompts and decided against it. Most of the prompt that we have follow some kind of "centered heading -> text below" pattern, which breaks if we change the `lineWrapping` for all prompts, and fixing that is very involved due to CSS constraints.

However, the `inform` function makes it possible to configure the `lineWrapping` inside of the prompt, thus, you can just do `$world.inform('The URL is https://galyleo.app/dashboards/0/drilldown-test.gd.json', {lineWrapping: false})` without the need to create a new component.

I do not want to step on anyone's toes, but a last thought: Are you sure it wouldn't be nicer to have a link in that prompt instead of a raw URL? You can get links like this:
`$world.inform(['The URL is ', null, 'here', { link: 'https://galyleo.app/dashboards/0/drilldown-test.gd.json'}])`
