### ISSUE TITLE
Connections aren't firing

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#78]
See the world "dataParser".    The textString on the entry morph is connected to the processInputCharacters method on the morph 'headerSpecifier", but as I type characters nothing happens.

**Comment by merryman** [comment]
That is because you *really* want to listen for the `input` signal instead. We can however make the input also fire a textString signal upon keyboard input
However note that this can have unintended consequences as textString may also be invoked in other situation where propagation is not supposed to happen.
Thoughts?
