### ISSUE TITLE
connect showing up multiple times in import

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#79]
Obviously, a user won't know which one to import.  Maybe the right connect should be preloaded?
![image](https://user-images.githubusercontent.com/656259/98849475-1eccab00-2408-11eb-9d2e-045d1a6856e7.png)

**Comment by merryman** [comment]
Well these are two independent libraries exposing a different function by the same name. Since you already had a signature of the method you assumed typed out, we can for these cases filter by number of arguments or highlight suggested items that match the signature more pronounced. However there are various cases were signature and name are the same and we still end up with this case.

**Comment by merryman** [comment]
@rickmcgeer we could solve this more comprehensively by adding typescript support in lively. For all the annoying side issues this requires us to solve it is exactly this case where a typesystem can give you the exact right choice.

**Comment by linusha** [comment]
Typescript support is a) not on the immediate road map, b) requires way more thought than we currently have put into it, and c) would probably require it's own ticket. Will close this for now.
