### ISSUE TITLE
Guidance on timing of initialization events

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#810]
**What would you like to achieve?**
One area where I constantly hit issues is the timing of actions on the initialization of Morphs, and when specific properties are instantiated.  There are four basic events that I'd like guidance on:

1. The Morph's constructor
2. `onLoad()`
3. `whenRendered()`
4. `addMorph()`/`openInWorld()`

Specifically, what I'd like to know is in which order these are called.   My guess, based on observation through experimentation, is:
1. The Morph's constructor
2. `onLoad()`
3. `addMorph()`/`openInWorld()`
4. `whenRendered()`

But I could be wrong

I'd also like to know when the physical properties of submorphs are available. 
Really clear documentation on this would be helpful to me and others

**Comment by merryman** [comment]
What you wrote in your suspected order of execution is basically correct.
I would explain as follows:

1. The Morph's constructor **or the deserialization of the morph from a snapshot**
2. `onLoad()`
3. `addMorph()`/`openInWorld()`
4. `whenRendered()` *Although we are planning to phase this out, since it is a remnant from the asynchronous render loop that we want to move away from.*
