### ISSUE TITLE
Boolean attributes overwritten in HTML Morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#817]
**Describe the bug**
The `video` tag in HTML takes Boolean attributes `autoplay`, `loop`, and `controls`.  The tag should be:
```
<video width="320" height="240" autoplay loop controls>
...
</video.
```
Which is what I type into the HTML Morph.  However, when I `edit HTML` from the menu, this is what appears in the editor box:
```
<video width="320" height="240" autoplay=""  loop="" controls="" >
...
</video>
```

**To Reproduce**
Just use any HTML Morph, any video, and put this into a method which sets the html onLoad to the video tag given, then edit HTML from the morph menue

**Setup**

- Windows
- Linux
- Docker

**Version**:
54e8e6aff13c2dd56f95ea89ccb1d5b129766394

**Comment by merryman** [comment]
According to the [HTML reference](https://www.w3schools.com/tags/att_video_autoplay.asp) the attributes `autoplay`, `loop` or `controls` are boolean attributes. This means that it does not matter what value they are assigned to, as long as they are listed they are considered to be truthy. The effect you observe when you reopen the HTML menu is a quirk of the browser who is not able to list attributes without a value since we use the `outerHTML()` function to retrieve the HTML code from the node.
I dunno if there is an easy way to get rid of this, but since it does not have any effect on the behavior, I would leave it at that for the time being. @linusha any thoughts?

**Comment by linusha** [comment]
A few thoughts on this:

1. As @merryman pointed out, those are boolean attributes. **This means, that the assigned value does not matter at all. You should be able to put anything, and it would work with all major browser.** Thus, you can just ignore the empy strings, as they are indeed an artifact of the `outerHTML` function.
2. This is probably obvious, but for the manipulation (setting/removing/...) of attributes there are dedicated DOM methods that should be used, and that all can cope with the empty strings or no value at all.
3. Autoplaying video is not always allowed by Chrome, which might seem like something is not working if you did not know about [these rules](https://developer.chrome.com/blog/autoplay/).
