### ISSUE TITLE
loadViaScript() is not present in frozen code

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#868]
**Describe the bug**
I have a page that relies on dynamic load of libraries from google, and the initialization code uses `loadViaScript` to load the google chart libraries.  However, in frozen code, the Google libraries aren't loading, and when I execute
```
await loadViaScript('https://www.gstatic.com/charts/loader.js');
```
I get the following:
```
VM547:1 Uncaught ReferenceError: loadViaScript is not defined
    at <anonymous>:1:1
```

**Comment by linusha** [comment]
I just bundled a JS file with the following `main` function

```js
export async function main () {
  await loadViaScript('https://www.gstatic.com/charts/loader.js');
  console.log(window.google.charts);
}
```

and upon opening the `index.html` I see the expected output in the console.

@merryman any ideas? Otherwise, this needs more context. E.g., where do you execute that to get the error message above? What bundle explicitly is not working? I could infer, that this is about GalyleoDashboard from what I know about it, but I'd prefer not having to do that...

**Comment by merryman** [comment]
@rickmcgeer We need more context, at least provide the entire module including the import where `loadViaScript` is called.

**Comment by rickmcgeer** [comment]
The repo is here: https://github.com/engageLively/galyleo-dashboard
The invocation is here: 
`$world.execCommand("open browser", {moduleName: "studio/dashboard-common.cp.js", packageName: "galyleo-dashboard", codeEntity: [{"name":"DashboardCommon","type":"class-decl"},{"name":"_loadGoogleChartPackages","type":"class-instance-method"}]});`

The deployed page is here: https://matt.engagelively.com/users/rick/published/studio-beta-en/index.html
