### ISSUE TITLE
Images from imgur don't load on PC

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#880]
**Describe the bug**
Every time I pull down an image, the default image can't be loaded.  This is in a Chrome browser under windows, running native (no Docker).  Presumably it's hitting a security issue somewhere.

There are no errors in the network tab or on the console, and I checked: the URL https://i.imgur.com/uGRFZEs.jpg loads just fine in another tab in the same browser.  Further, other images load well, e.g. https://avatars.githubusercontent.com/u/2310032?s=280&v=4

This obviously isn't a big deal to me, but it doesn't look great as we get closer to release, and I'm wondering if this will hit with other images.

**To Reproduce**
It's clear this works fine for you guys, so I don't know how to reproduce this.  I'm running Chrome on Windows 11, nothing special with security, and for all the world it looks like the request wasn't made.  The only thing I see in the network tab is a couple of 200's for a data png image

**Screenshots**

![Screenshot 2023-06-05 194038](https://github.com/LivelyKernel/lively.next/assets/656259/bd0eed14-b61c-43a2-bf67-6389f8cdbacb)
![Screenshot 2023-06-05 194052](https://github.com/LivelyKernel/lively.next/assets/656259/7914cbab-9520-4a7e-ba38-ece6e3e5fc6e)

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
https://avatars.githubusercontent.com/u/2310032?s=280&v=4

**Comment by linusha** [comment]
AFAIK, most security issues would manifest inside of the console somehow. Since you are not able to observe a request this sound like a cache issue to me that might be resolved by clearing the application storage inside of the dev tools.

Anyways, if I understood you correctly, this is only about the default image and does not effect anything else? I just went ahead and exchanged that, so that we do not need to load it from the web anymore and now it's the lively logo. See #882.

**Comment by merryman** [comment]
We replaced the default image for image morphs created via top bar in #882, as mentioned by @linusha.
This should have fixed the issue reported as per @rickmcgeer.
