### ISSUE TITLE
Server crashing on attempt to load a project

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#909]
**Describe the bug**
The page loads up to the background screen with the status popup "Loading Project...." and then hangs.  The console is showing failure to connect to a websocket.  The server log shows that the server has crashed, with the following error message:
```
2023-07-02T15:47:07.562Z info: [report-world-load] rickmcgeer logged in at aLivelyWorld [undefined] 127.0.0.1
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: spawn /bin/bash ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/bash',
  path: '/bin/bash',
  spawnargs: [
    '-c',
    'source /home/rick/lively.next/lively.shell/bin/lively.profile; git checkout package.json'
  ]
}
```

The two bash commands work fine from the bash command line, so my _guess_ is that the script needs to be:
```
 'source /home/rick/lively.next/lively.shell/bin/lively.profile; cd /home/rick/lively.next/local_projects/galyleo-dashboard; git checkout package.json'
```
But that's only a guess.
Playgrounds work fine, so it is certainly something with a project load.
**To Reproduce**
do a `git clone git@github.com:engageLively/galyleo-dashboard.git` in the `local_projects` directory and then open the project from the dashboard window

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows (note that I am running this under WSL, Ubuntu)

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
5cecb8d2030617b92320cefc9ea4e63439e36630

**Comment by rickmcgeer** [comment]
I reproduced this error on a Mac

**Comment by linusha** [comment]
It is recommended that you clone projects via the dialogue that is accessible after clicking "New Project" on the dashboard.
![grafik](https://github.com/LivelyKernel/lively.next/assets/14252419/ee02ae9d-bd14-453e-acb7-48138a7218c3)
Simply running `git clone` will usually not suffice.
The reason is that we expect projects to reside in folders that are named following the schema _<owner>--<name>_. In your case, this is _engageLively--galyleo-dashboard_. **Since you have the folder already, you can also just rename it to the aforementioned name and you should be good to go!** In the future, if you want to use `git clone` you can also use specify the name at the end of the command, like `git clone name_of_the_folder`.
