### ISSUE TITLE
Incomplete organization list for new project

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#942]
**Describe the bug**
engageLively isn't appearing in my list of organizations for a new project.  I have eight organizations on top of my personal repo

**To Reproduce**
I assume that this will happen for others as well, but I'm not sure.

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/cd15428d-beb7-4379-8681-cff91c8a6121)

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
89e6003509edfbeeb9deceadaebabf82903dbe60

**Comment by merryman** [comment]
@linusha I believe this is because rick has not granted access permission of the EngageLively Organization via his account, correct?

**Comment by rickmcgeer** [comment]
I was able to create the galyleo-dashboard project earlier.

**Comment by rickmcgeer** [comment]
I can experiment with this.  How can I grant access permission?

**Comment by linusha** [comment]
It probably has nothing to do with permissions, since for @merryman the org works just fine.
The underlying problem here is very likely that we retrieve the available organizations exactly once, upon login. I think you are logged in for longer than the permission for the org has been granted. Logging out and back in again should fix this.

I will also push a fix shortly, that makes this unnecessary.

**Comment by rickmcgeer** [comment]
Logout and re-login fixed this, thanks, @linusha .  You were exactly right.
