### ISSUE TITLE
The New fonts are ugly and dysfunctional

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#974]
**Describe the Feature**
I'd really prefer fixed-width sans-serif fonts in an IDE.  This isn't just an aesthetic issue; fixed-width fonts are very useful when we're trying to indent by a fixed number of spaces.  Up until the latest release, we had very nice fonts everywhere.  However,  now at least the browser editor, Object Editor, Object Inspector, and JavaScript workspace all seem to have a Times font.  Further, the icon beside the class name in the Object Editor was much more evocative than the empty square that appears now

See, for example, this Object Editor:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/89813cf6-662a-4ddf-a9b6-555f43b7fa95)

And this Object Inspector:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/e4ae5f2e-6f7b-41d6-acde-30e35f4190f5)

**Graphics**
If applicable, provide screenshots/videos of similar ideas in other software.

**Implementation Details**
I don't think it's any more complicated than using a standard fixed-width font and using the old icons for the OE and OI.  I was really very happy with this feature in Lively up until the current version:
34f27b39a9805265b86369a67ee0ffe665dc1f8e

**Comment by linusha** [comment]
This is not what it should look like, the font change should be a transparent change in the sense that the underlying implementation has changed, but everything should look the same.

I suspect that #975 and #973 are related as well, as I think the text measuring that is heavily used to things like the placement of the cursor and selections is off.

Have you run `./install.sh` after updating lively, or `make artifacts`? It seems to me like the font import via CSS fails all together. Since that one is injected by the landing page/loading screen, a rebuild is mandatory to get it to work.

I deem this problem absolutely with top most priority, please get back to me ASAP.

**Comment by linusha** [comment]
@rickmcgeer what's the status on this? Does rebuilding the landing-page/loading-screen resolve this?
